// <auto-generated />
using System;
using Gimnasio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gimnasio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260301063223_RemoveDisenoMarketingFK")]
    partial class RemoveDisenoMarketingFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gimnasio.Models.AdminLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NegocioAfectado")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("Gimnasio.Models.CategoriaProducto", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.HasIndex("NegocioId");

                    b.ToTable("CategoriasProducto");
                });

            modelBuilder.Entity("Gimnasio.Models.Cita", b =>
                {
                    b.Property<Guid>("CitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDeActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreCliente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreEmpleado")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreServicio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecioServicio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RecordatorioEnviado")
                        .HasColumnType("bit");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CitaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("NegocioId", "Estado")
                        .HasDatabaseName("IX_Citas_NegocioId_Estado");

                    b.HasIndex("NegocioId", "FechaHoraInicio")
                        .HasDatabaseName("IX_Citas_NegocioId_FechaHoraInicio");

                    b.HasIndex("EmpleadoId", "FechaHoraInicio", "FechaHoraFin")
                        .HasDatabaseName("IX_Citas_EmpleadoId_Horario");

                    b.HasIndex("RecordatorioEnviado", "Estado", "FechaHoraInicio")
                        .HasDatabaseName("IX_Citas_Recordatorio");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("Gimnasio.Models.Cliente", b =>
                {
                    b.Property<Guid>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Dias")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EsDiario")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaDeActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaQueTermina")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GymNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UltimoRecordatorioCobro")
                        .HasColumnType("datetime2");

                    b.HasKey("ClienteId");

                    b.HasIndex("GymNegocioId");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("IX_Clientes_NegocioId");

                    b.HasIndex("NegocioId", "FechaQueTermina")
                        .HasDatabaseName("IX_Clientes_NegocioId_FechaQueTermina");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Gimnasio.Models.ComisionVendedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DiasContratados")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPagoPago")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MontoComision")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreNegocio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreVendedor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Pagada")
                        .HasColumnType("bit");

                    b.Property<decimal>("PrecioNegocio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoComision")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ComisionesVendedor");
                });

            modelBuilder.Entity("Gimnasio.Models.DetalleOrdenVenta", b =>
                {
                    b.Property<Guid>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("OrdenVentaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DetalleId");

                    b.HasIndex("OrdenVentaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesOrdenVenta");
                });

            modelBuilder.Entity("Gimnasio.Models.DisenoMarketing", b =>
                {
                    b.Property<Guid>("DisenoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Alto")
                        .HasColumnType("int");

                    b.Property<int>("Ancho")
                        .HasColumnType("int");

                    b.Property<string>("CanvasJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThumbnailDataUri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DisenoId");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("IX_DisenosMarketing_NegocioId");

                    b.ToTable("DisenosMarketing");
                });

            modelBuilder.Entity("Gimnasio.Models.Empleado", b =>
                {
                    b.Property<Guid>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("IX_Empleados_NegocioId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Gimnasio.Models.FacturaElectronica", b =>
                {
                    b.Property<Guid>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaveAcceso")
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.Property<string>("CompradorDireccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompradorEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompradorIdentificacion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CompradorRazonSocial")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CompradorTipoIdentificacion")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("DetalleItemsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Establecimiento")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("EstadoSri")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoIntento")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPagoSri")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal>("ImporteTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IntentosEnvio")
                        .HasColumnType("int");

                    b.Property<string>("MensajesSri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoIva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumeroAutorizacion")
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.Property<string>("NumeroCompleto")
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("PuntoEmision")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid?>("ReciboId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RidePdf")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Secuencial")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDescuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSinImpuestos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("XmlAutorizadoComprimido")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("FacturaId");

                    b.HasIndex("ReciboId");

                    b.HasIndex("NegocioId", "ClaveAcceso")
                        .IsUnique()
                        .HasDatabaseName("IX_FacturasElectronicas_NegocioId_ClaveAcceso")
                        .HasFilter("[ClaveAcceso] IS NOT NULL");

                    b.HasIndex("NegocioId", "EstadoSri")
                        .HasDatabaseName("IX_FacturasElectronicas_NegocioId_EstadoSri");

                    b.HasIndex("NegocioId", "FechaEmision")
                        .HasDatabaseName("IX_FacturasElectronicas_NegocioId_FechaEmision");

                    b.HasIndex("NegocioId", "Establecimiento", "PuntoEmision", "Secuencial")
                        .IsUnique()
                        .HasDatabaseName("IX_FacturasElectronicas_Numeracion")
                        .HasFilter("[Establecimiento] IS NOT NULL AND [PuntoEmision] IS NOT NULL");

                    b.ToTable("FacturasElectronicas");
                });

            modelBuilder.Entity("Gimnasio.Models.Gym", b =>
                {
                    b.Property<Guid>("NegocioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AceptoTerminos")
                        .HasColumnType("bit");

                    b.Property<string>("AgenteRetencion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CertificadoP12Base64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificadoPasswordEncriptado")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CodigoEstablecimiento")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ContribuyenteEspecial")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DiasPagados")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DireccionMatriz")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DuenoNegocio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EsPrueba")
                        .HasColumnType("bit");

                    b.Property<bool>("FacturacionElectronicaActiva")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAceptoTerminos")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDeActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NegocioBloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("NegocioNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("ObligadoContabilidad")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecioSuscripcion")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PuntoEmision")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RegimenContribuyente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ruc")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("SriAmbiente")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoNegocio")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("VendedorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NegocioId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Negocios_Email_Unique")
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Negocios");
                });

            modelBuilder.Entity("Gimnasio.Models.Horario", b =>
                {
                    b.Property<Guid>("HorarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsDiaLibre")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoraFin")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HoraInicio")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoHorario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("HorarioId");

                    b.HasIndex("EmpleadoId", "DiaSemana")
                        .IsUnique()
                        .HasDatabaseName("IX_Horarios_EmpleadoId_DiaSemana")
                        .HasFilter("[TipoHorario] = 'regular' AND [DiaSemana] IS NOT NULL");

                    b.HasIndex("EmpleadoId", "Fecha")
                        .IsUnique()
                        .HasDatabaseName("IX_Horarios_EmpleadoId_Fecha")
                        .HasFilter("[TipoHorario] = 'excepcion' AND [Fecha] IS NOT NULL");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("Gimnasio.Models.LeadVendedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Atendido")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AtendidoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AtendidoPorNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NombreNegocio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Origen")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("LeadsVendedor");
                });

            modelBuilder.Entity("Gimnasio.Models.Logs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreCliente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("IX_Logs_NegocioId");

                    b.HasIndex("NegocioId", "Fecha")
                        .HasDatabaseName("IX_Logs_NegocioId_Fecha");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Gimnasio.Models.MenuRestaurante", b =>
                {
                    b.Property<Guid>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContenidoHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Estilo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PrecioFijo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoMenu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MenuId");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("IX_MenusRestaurante_NegocioId");

                    b.ToTable("MenusRestaurante");
                });

            modelBuilder.Entity("Gimnasio.Models.Mesa", b =>
                {
                    b.Property<Guid>("MesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("MesaId");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("IX_Mesas_NegocioId");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("Gimnasio.Models.MetodoPago", b =>
                {
                    b.Property<Guid>("MetodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("EsPredeterminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenQR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instrucciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreTitular")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroCuenta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("MetodoPagoId");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("IX_MetodosPago_NegocioId");

                    b.HasIndex("NegocioId", "IsActive")
                        .HasDatabaseName("IX_MetodosPago_NegocioId_IsActive");

                    b.ToTable("MetodosPago");
                });

            modelBuilder.Entity("Gimnasio.Models.MovimientoInventario", b =>
                {
                    b.Property<Guid>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nota")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StockAnterior")
                        .HasColumnType("int");

                    b.Property<int>("StockNuevo")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MovimientoId");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("IX_MovimientosInventario_NegocioId");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("Gimnasio.Models.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreCliente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("IX_Notificaciones_NegocioId");

                    b.HasIndex("NegocioId", "ClienteId", "FechaCreacion")
                        .HasDatabaseName("IX_Notificaciones_NegocioId_ClienteId_Fecha");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Gimnasio.Models.OrdenVenta", b =>
                {
                    b.Property<Guid>("OrdenVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DireccionEntrega")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("EmpleadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GastosAdicionales")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("MesaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MontoIva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreCliente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroConfirmacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroOrden")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeIva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ReciboId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoOrden")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrdenVentaId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("MesaId");

                    b.HasIndex("NegocioId");

                    b.HasIndex("ReciboId");

                    b.ToTable("OrdenesVenta");
                });

            modelBuilder.Entity("Gimnasio.Models.PagoCita", b =>
                {
                    b.Property<Guid>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetalleExtra")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsRegalo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MontoExtra")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoServicio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoRegalo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreCliente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreServicio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Propina")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PagoId");

                    b.HasIndex("CitaId")
                        .IsUnique()
                        .HasDatabaseName("IX_PagosCita_CitaId_Unique");

                    b.ToTable("PagosCita");
                });

            modelBuilder.Entity("Gimnasio.Models.Producto", b =>
                {
                    b.Property<Guid>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoriaProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostoCompra")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDeActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Receta")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaProductoId");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("IX_Productos_NegocioId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Gimnasio.Models.Recibo", b =>
                {
                    b.Property<Guid>("ReciboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Concepto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContenidoHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinatarioEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DestinatarioNombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NegocioNombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumeroRecibo")
                        .HasColumnType("int");

                    b.Property<string>("TipoRecibo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReciboId");

                    b.HasIndex("NegocioId", "FechaCreacion")
                        .HasDatabaseName("IX_Recibos_NegocioId_FechaCreacion");

                    b.HasIndex("NegocioId", "NumeroRecibo")
                        .HasDatabaseName("IX_Recibos_NegocioId_NumeroRecibo");

                    b.ToTable("Recibos");
                });

            modelBuilder.Entity("Gimnasio.Models.Reserva", b =>
                {
                    b.Property<Guid>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraReserva")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MesaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ReservaId");

                    b.HasIndex("MesaId");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("IX_Reservas_NegocioId");

                    b.HasIndex("NegocioId", "FechaHoraReserva")
                        .HasDatabaseName("IX_Reservas_NegocioId_FechaHora");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Gimnasio.Models.ServicioNegocio", b =>
                {
                    b.Property<Guid>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("EsCombo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDeActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemsIncluidos")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ServicioId");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("IX_ServiciosNegocio_NegocioId");

                    b.ToTable("ServiciosNegocio");
                });

            modelBuilder.Entity("Gimnasio.Models.Sugerencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NegocioNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("IX_Sugerencias_NegocioId");

                    b.ToTable("Sugerencias");
                });

            modelBuilder.Entity("Gimnasio.Models.Vendedor", b =>
                {
                    b.Property<Guid>("VendedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AceptoTerminos")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaAceptoTerminos")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("NegociosCreados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreBanco")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroCedula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NumeroCuenta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VendedorId");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("Gimnasio.Models.CategoriaProducto", b =>
                {
                    b.HasOne("Gimnasio.Models.Gym", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Gimnasio.Models.Cita", b =>
                {
                    b.HasOne("Gimnasio.Models.Cliente", "Cliente")
                        .WithMany("Citas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Gimnasio.Models.Empleado", "Empleado")
                        .WithMany("Citas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Gimnasio.Models.Gym", "Negocio")
                        .WithMany("Citas")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gimnasio.Models.ServicioNegocio", "Servicio")
                        .WithMany("Citas")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Negocio");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Gimnasio.Models.Cliente", b =>
                {
                    b.HasOne("Gimnasio.Models.Gym", null)
                        .WithMany("Clientes")
                        .HasForeignKey("GymNegocioId");
                });

            modelBuilder.Entity("Gimnasio.Models.DetalleOrdenVenta", b =>
                {
                    b.HasOne("Gimnasio.Models.OrdenVenta", "OrdenVenta")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gimnasio.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OrdenVenta");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Gimnasio.Models.Empleado", b =>
                {
                    b.HasOne("Gimnasio.Models.Gym", "Negocio")
                        .WithMany("Empleados")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Gimnasio.Models.FacturaElectronica", b =>
                {
                    b.HasOne("Gimnasio.Models.Gym", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gimnasio.Models.Recibo", "Recibo")
                        .WithMany()
                        .HasForeignKey("ReciboId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Negocio");

                    b.Navigation("Recibo");
                });

            modelBuilder.Entity("Gimnasio.Models.Horario", b =>
                {
                    b.HasOne("Gimnasio.Models.Empleado", "Empleado")
                        .WithMany("Horarios")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Gimnasio.Models.MenuRestaurante", b =>
                {
                    b.HasOne("Gimnasio.Models.Gym", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Gimnasio.Models.Mesa", b =>
                {
                    b.HasOne("Gimnasio.Models.Gym", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Gimnasio.Models.MetodoPago", b =>
                {
                    b.HasOne("Gimnasio.Models.Gym", "Negocio")
                        .WithMany("MetodosPago")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Gimnasio.Models.OrdenVenta", b =>
                {
                    b.HasOne("Gimnasio.Models.Empleado", "Repartidor")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Gimnasio.Models.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Gimnasio.Models.Gym", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gimnasio.Models.Recibo", "Recibo")
                        .WithMany()
                        .HasForeignKey("ReciboId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Mesa");

                    b.Navigation("Negocio");

                    b.Navigation("Recibo");

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("Gimnasio.Models.PagoCita", b =>
                {
                    b.HasOne("Gimnasio.Models.Cita", "Cita")
                        .WithOne("Pago")
                        .HasForeignKey("Gimnasio.Models.PagoCita", "CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("Gimnasio.Models.Producto", b =>
                {
                    b.HasOne("Gimnasio.Models.CategoriaProducto", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaProductoId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Gimnasio.Models.Reserva", b =>
                {
                    b.HasOne("Gimnasio.Models.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Gimnasio.Models.Gym", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Gimnasio.Models.ServicioNegocio", b =>
                {
                    b.HasOne("Gimnasio.Models.Gym", "Negocio")
                        .WithMany("Servicios")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Gimnasio.Models.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Gimnasio.Models.Cita", b =>
                {
                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Gimnasio.Models.Cliente", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("Gimnasio.Models.Empleado", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Gimnasio.Models.Gym", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Clientes");

                    b.Navigation("Empleados");

                    b.Navigation("MetodosPago");

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("Gimnasio.Models.OrdenVenta", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Gimnasio.Models.ServicioNegocio", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
